name: Rebuild seed files

# ──────────────────────────────────────────────────────────────
# Triggers
# • Every Monday at 02:00 UTC
# • Manual “Run workflow” button in the GitHub UI
# ──────────────────────────────────────────────────────────────

on:
  schedule:
    - cron: '0 2 * * 1'              # every Monday 02:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. Install script deps
      - run: pip install --no-cache-dir mysql-connector-python

      # 4. Rebuild SQL files
      - name: Build SQL seeds
        run: python scripts/build_seeds.py

      # 5. Commit & push if ANY tracked file changed
      - name: Commit updated seeds
        run: |
          # stage everything (new + changed + deletes)
          git add -A

          # if nothing staged, quit quietly
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          # configure committer
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # commit & push
          git commit -m "auto: refresh seed files $(date -u +'%Y-%m-%d')"
          git push
