name: Rebuild seed files

# ──────────────────────────────────────────────────────────────
# Triggers
# • Every Monday at 02:00 UTC
# • Manual “Run workflow” button in the GitHub UI
# ──────────────────────────────────────────────────────────────

on:
  schedule:
    - cron: '0 2 * * 1'        # every Monday 02:00 UTC
  workflow_dispatch:         # manual trigger

permissions:
  contents: write            # allow commits

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --no-cache-dir mysql-connector-python

      - name: Build SQL seeds
        run: python scripts/build_seeds.py

      - name: Commit updated seeds (only /data)
        run: |
          # stage SQL + JSON in data/
          git add data/*.sql data/states-and-lgas-and-wards.json || true

          # nothing to commit?
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          # configure committer
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # commit & push
          git commit -m "ci: refresh seed files $(date -u +'%Y-%m-%d')"
          git push
